name: Create Pull Request from development to main

on:
  push:
    branches:
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: 'Sync development to main'
          body: |
            This pull request was created automatically by a GitHub Action.
          draft: false
